var datos  =  {
    "nombre" : "Dilan",
    "Edad" : "19",
    "Carrera" : "Ingenieria en Software",

    "deportes" : {
       "deporte1" : "Basketball",
       "deporte2" : "correr" 
    },
       "Pasatiempos" : {
           "Pasatiempo1" : "escuchar musica",
           "Pasatiempo2" : "ver series" 
       },
           "Generos musicales favoritos" : {
               "reggaeton" : true,
               "trap" : true,
               "rap" : true,
               "cumbias" : true 
           },
               "series favoritas" : {
                   "bob esponja" : true,
                   "flash" : true,
                   "prison break" : true 
               }
}
console.log(datos);
